[package]
name = "certified-http"
version = "0.1.2"
description = "A single interface that stores key-value pairs and certifies their hashes for use as certified variables or assets."
repository = "https://github.com/infu/certified-http"

[dependencies]
base = "0.8.3"
ic-certification = "0.1.0"
sha2 = "0.0.2"

