[dependencies]
base = "0.8.3"
StableRBTree = "https://github.com/canscale/StableRBTree#master"
ic-certification = "0.1.0"
motoko-sha = "https://github.com/enzoh/motoko-sha#master"
StableHashMap = "https://github.com/canscale/StableHashMap#master"